### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'data/cityscapes/Label256Full/****

### ISSUE THREAD

**Issue by yifanjiang19** [CQFIO/PhotographicImageSynthesis#3]
After I run `python download_models.py`,
I run `python demo_256p.py`
and it turns out:
Traceback (most recent call last):
  File "demo_256p.py", line 115, in <module>
    label_images[ind]=helper.get_semantic_map("data/cityscapes/Label256Full/%08d.png"%ind)#training label
  File "/home/ah/disk/jiangyifan/PhotographicImageSynthesis/helper.py", line 15, in get_semantic_map
    semantic=scipy.misc.imread(path)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 156, in imread
    im = Image.open(name)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2258, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/cityscapes/Label256Full/00002618.png'

The bugs also happened when I run `python demo_512p.py`

**Comment by yueruchen** [comment]
Maybe the variable `ind` shouldn't be random.

**Comment by CQFIO** [comment]
This code was designed for the Cityscapes dataset. You also need to download the Cityscapes dataset for training and have the 2975 training images and labels as "data/cityscapes/RGB256Full/%08d.png"%ind and "data/cityscapes/Label256Full/%08d.png"%ind where ind is from 1 to 2975.
